### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by jiezhiyong** [utom/tinypng-for-automator#1]
hi,thanks for you work,i think it's very convenient.
but i found a serious bug:
when i complete,my image just broken

![image](https://cloud.githubusercontent.com/assets/9351855/20873238/79e4489e-bae0-11e6-91d5-c8efc9950d73.png)

buy the way,it's too slow.
sorry for my poor English.

**Comment by utom** [comment]
你的网络问题~ 导致的!
